artifact_location: file:C:/Users/sarah/Documents/GitHub/rakuten-mlops/${MLFLOW_TRACKING_URI}/0
creation_time: 1747136061026
experiment_id: '0'
last_update_time: 1747136061026
lifecycle_stage: active
name: Default
