name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v3

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: ⚙️ Installer les dépendances Airflow
        run: pip install -r airflow/requirements.txt

      - name: ⚙️ Installer les dépendances du training
        run: pip install -r src/training/requirements.txt

      - name: ✅ Vérifier l’import des modules principaux
        run: |
          python -c "import sklearn"
          python -c "import xgboost"
          python -c "import mlflow"

